<?php
/**
 * @var \Ivan\NewsFrontendUi\Block\News\Index\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div data-bind="scope: 'news'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "news": {
                        "component": "Ivan_NewsFrontendUi/js/news",
                        "getListUrlPath": "<?= $escaper->escapeJs($block->getListUrlPath()); ?>"
                    }
                }
            }
        }
    }
</script>
