<?php
/**
 * @var \Ivan\ModuleCreator\Block\Index\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div data-bind="scope: 'module-creator'" class="module-creator-container">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "module-creator": {
                        "component": "Ivan_ModuleCreator/js/module_creator",
                        "noCreatorsMessage": "<?= $escaper->escapeJs(__("Creators didn't find in the system."));?>",
                        "creatorsInitData": <?= /* @noEscape */ $block->getCreatorsInitData(); ?>
                    }
                }
            }
        }
    }
</script>
